# Generated by Django 4.1.4 on 2022-12-12 07:45

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
